ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "hello_labdata_pmv"
  description: "Labdata Hello Python Package 2022"
  execute: 
    enabled: false
  twitter-card: true
  open-graph: true
  reader-mode: true
  repo-branch: main
  repo-url: https://github.com/pmatheusvinhas/hello-labdata-pmv/
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: https://github.com/pmatheusvinhas/hello-labdata-pmv/
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
